services:
  - type: web
    name: bullbear-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bullbear-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: bullbear-db
    region: oregon
    plan: starter
